-- Active: 1697616242142@@127.0.0.1@5432@srezdb
CREATE DATABASE SREZdb;

CREATE TABLE "USER" (
    USER_ID INT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    "LOGIN" VARCHAR(255) NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE "ORDER" (
    ORDER_ID INT PRIMARY KEY,
    USER_ID INT,
    ORDER_DATE DATE,
    TOTAL_AMOUNT DECIMAL(10, 2),
    FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID)
);

CREATE TABLE "SERVICE" (
    SERVICE_ID INT PRIMARY KEY,
    SERVICENAME VARCHAR(255) NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    SERVICE_COST DECIMAL(10, 2)
);

CREATE TABLE "ORDER_SERVICE" (
    ORDER_ID INT,
    SERVICE_ID INT,
    PRIMARY KEY (ORDER_ID, SERVICE_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES "ORDER"(ORDER_ID),
    FOREIGN KEY (SERVICE_ID) REFERENCES "SERVICE"(SERVICE_ID)
);


INSERT INTO "USER" VALUES
(1, 'John Doe', 'johndoe', 'password123', 'john.doe@example.com'),
(2, 'Jane_Smith', 'SmithJanie', 'qwerty123', 'jane.smith@example.com');

INSERT INTO "ORDER" VALUES
(101, 1, '2023-01-15', 50.00),
(102, 2, '2023-01-16', 75.50);

INSERT INTO "SERVICE" VALUES
(201, 'Web Development', 'Website creation', 500.00),
(202, 'Graphic Design', 'Logo design', 200.00);

INSERT INTO "ORDER_SERVICE" VALUES
(101, 201),
(101, 202),
(102, 202),
(102, 201);